import { Link } from 'react-router-dom'
import { Project } from '../data/projects'
import { ArrowLink } from './Shell'
import { useLanguage } from '../locales'

export function ProjectCard({ project, index }: { project: Project; index: number }) {
  const { t, language } = useLanguage()
  const text = (value: string) => t(value)
  const arrow = language === 'fa' ? '←' : '→'
  const preview = project.id === 'elixia' ? <><strong>{language === 'fa' ? 'تمرین امروز' : "Today's Workout"}</strong><b>🔥 {language === 'fa' ? 'سینه و پشت بازو' : 'Chest & Triceps'}</b><span>{language === 'fa' ? 'برنامه تغذیه' : 'Nutrition Plan'} <em>2,340 kcal</em></span></> : project.id === 'co-up' ? <><strong>{language === 'fa' ? 'صندلی‌های خالی' : 'Available Seats'}</strong><b>A12　 A13　 A14</b><span>{language === 'fa' ? 'اتاق جلسه' : 'Meeting Room'} <em>{language === 'fa' ? 'اتاق ۰۲ · موجود' : 'Room 02 · Available'}</em></span></> : project.id === 'inotex' ? <><strong>INOTEX</strong><b>{language === 'fa' ? 'غرفه‌داران　 رویدادها　 شرکت‌ها' : 'Exhibitors　 Events　 Companies'}</b><span>{language === 'fa' ? 'دستیار هوشمند' : 'Ask AI Assistant'} <em>{language === 'fa' ? 'هر سوالی دارید بپرسید ←' : 'Ask anything →'}</em></span></> : project.id === 'oiec' ? <><strong>{language === 'fa' ? 'موجودی' : 'Inventory'}</strong><b>{language === 'fa' ? 'کد قدیمی　←　کد جدید' : 'Old Code　→　New Code'}</b><span>{language === 'fa' ? 'تبدیل هوشمند' : 'AI Transformation'} <em>{language === 'fa' ? 'در حال پردازش...' : 'Processing...'}</em></span></> : <><strong>{language === 'fa' ? 'پروژه شماره ۵' : 'Project #5'}</strong><b>{text('Details coming soon.')}</b><span>{text('Project Preview')} <em>—</em></span></>
  return <article className="project-card"><div className="card-top"><span className="project-number">{String(index + 1).padStart(2, '0')}</span><span className="status"><i /> {text(project.status)}</span></div><div className={`project-art art-${project.id}`}><span className="preview-label">{text('PROJECT PREVIEW')}</span><div className="mock-window"><div className="mock-bar"><i /><i /><i /><b>{project.title}</b></div><div className="mock-content">{preview}</div></div></div><p className="eyebrow">{text(project.category)}</p><h3>{project.title}</h3><p className="muted">{text(project.description)}</p><div className="tags">{project.technologies.map(technology => <span key={technology}>{text(technology)}</span>)}</div><div className="card-links"><Link className="text-link" to={`/projects/${project.id}`}>{text('View Case Study')} <span>{arrow}</span></Link>{project.projectUrl && <ArrowLink href={project.projectUrl}>{text(project.id === 'elixia' ? 'Open Project' : project.id === 'oiec' ? 'Client Website' : 'Open Application')}</ArrowLink>}</div>{project.organizationUrl && <ArrowLink href={project.organizationUrl}>{text('Official Website')}</ArrowLink>}</article>
}
